import { describe, expect, it } from 'vitest';
import { buildImageKey, presignWith, type StorageSettings } from './s3.js';

/**
 * The signing implementation, checked against vectors produced by **botocore**
 * — AWS's own SigV4 implementation — and verified to match it byte for byte,
 * signature and URL alike.
 *
 * Signing code that has never been run against a known-good signature is
 * indistinguishable from broken code until the first upload fails, and it
 * would fail in a browser against MinIO, a long way from here. The vectors
 * below were generated by driving `botocore.auth.S3SigV4QueryAuth` over the
 * same inputs; `scripts/verify-sigv4.mjs` re-runs that comparison against a
 * live botocore when one is available.
 */
const AWS_EXAMPLE: StorageSettings = {
  endpoint: 'https://s3.amazonaws.com',
  region: 'us-east-1',
  bucket: 'examplebucket',
  accessKey: 'AKIAIOSFODNN7EXAMPLE',
  // AWS's published example key. Not a credential: it appears verbatim in
  // their documentation and grants nothing.
  secretKey: 'wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY',
  forcePathStyle: false,
};

/** The MinIO shape the compose stack runs: path style, local endpoint. */
const MINIO: StorageSettings = {
  endpoint: 'http://localhost:9000',
  region: 'us-east-1',
  bucket: 'howlow-dev',
  accessKey: 'minioadmin',
  secretKey: 'minioadmin-secret',
  forcePathStyle: true,
};

const AT = new Date('2026-09-16T06:50:45Z');

describe('SigV4 presigning matches botocore', () => {
  it('signs a virtual-hosted GET', () => {
    const result = presignWith(AWS_EXAMPLE, {
      method: 'GET',
      key: 'test.txt',
      expiresInSeconds: 86_400,
      now: AT,
    });
    expect(result.url.split('?')[0]).toBe('https://examplebucket.s3.amazonaws.com/test.txt');
    expect(result.signature).toBe('b5ab1465332fe99c36dabbeb2a8dbf1dba9cf5b01070bf0294752e2bfc7a3bde');
  });

  it('signs a path-style PUT for a nested key', () => {
    const key =
      'products/11111111-1111-4111-8111-111111111111/22222222-2222-4222-8222-222222222222/33333333-3333-4333-8333-333333333333.jpg';
    const result = presignWith(MINIO, {
      method: 'PUT',
      key,
      expiresInSeconds: 900,
      now: AT,
    });
    expect(result.url.split('?')[0]).toBe(`http://localhost:9000/howlow-dev/${key}`);
    expect(result.signature).toBe('59bbbc5261789c80e3aaa424ae403bef4e5e5777385b7acde1d00646a973bbac');
  });

  /**
   * Content type and length are part of the signature, so an upload slot
   * issued for a 2 KB PNG cannot be replayed to push something else.
   */
  it('signs the content type and length of an upload', () => {
    const result = presignWith(MINIO, {
      method: 'PUT',
      key: 'products/a/b/c.png',
      expiresInSeconds: 900,
      signedHeaders: { 'content-type': 'image/png', 'content-length': '2048' },
      now: AT,
    });
    expect(result.url).toContain('X-Amz-SignedHeaders=content-length%3Bcontent-type%3Bhost');
    expect(result.signature).toBe('0290ab0585383876f19cd56220b0792e6e0b7331baf82bb90c8e3dedf196e868');
    // The client must send them back, so they are returned alongside the URL.
    expect(result.headers).toEqual({ 'content-type': 'image/png', 'content-length': '2048' });
  });

  it('signs a DELETE against the configured region', () => {
    const result = presignWith(
      { ...MINIO, region: 'eu-west-1' },
      { method: 'DELETE', key: 'products/a/b/c.webp', expiresInSeconds: 60, now: AT },
    );
    expect(result.signature).toBe('84765a5e6fae5281c9e834198c7691ead6dcc30bf6e4f33cd913a057b42219b1');
  });

  it('produces a different signature for any change to a signed value', () => {
    const base = {
      method: 'PUT' as const,
      key: 'products/a/b/c.png',
      expiresInSeconds: 900,
      now: AT,
    };
    const signatures = new Set([
      presignWith(MINIO, base).signature,
      presignWith(MINIO, { ...base, key: 'products/a/b/d.png' }).signature,
      presignWith(MINIO, { ...base, method: 'GET' }).signature,
      presignWith(MINIO, { ...base, expiresInSeconds: 901 }).signature,
      presignWith(MINIO, { ...base, now: new Date(AT.getTime() + 1000) }).signature,
      presignWith({ ...MINIO, region: 'eu-west-1' }, base).signature,
      presignWith({ ...MINIO, bucket: 'other' }, base).signature,
    ]);
    expect(signatures.size).toBe(7);
  });

  /**
   * S3 expects `!'()*` percent-escaped, which `encodeURIComponent` leaves
   * alone. Generated keys are only hex, hyphens, slashes and a dot, so this
   * never fires in production — it is here so the encoder stays correct if a
   * future caller introduces richer keys.
   */
  it('percent-escapes characters encodeURIComponent would leave bare', () => {
    const result = presignWith(MINIO, {
      method: 'GET',
      key: "products/a/it's (a) test*.jpg",
      expiresInSeconds: 300,
      now: AT,
    });
    const path = result.url.split('?')[0] ?? '';
    expect(path).toContain('%27');
    expect(path).toContain('%28');
    expect(path).toContain('%2A');
    expect(path).not.toMatch(/['()*]/);
    // The separators are not escaped; only the segments are.
    expect(path).toContain('/howlow-dev/products/a/');
  });
});

describe('object keys', () => {
  const owner = {
    sellerId: '11111111-1111-4111-8111-111111111111',
    productId: '22222222-2222-4222-8222-222222222222',
  };

  /**
   * Keys are built only from server-side values. Path traversal and
   * cross-seller overwrites are impossible by construction rather than
   * filtered out, because no caller-supplied string reaches the key.
   */
  it('builds a key under the owning seller and product prefix', () => {
    const key = buildImageKey({ ...owner, contentType: 'image/png' });
    expect(key).toMatch(
      /^products\/11111111-1111-4111-8111-111111111111\/22222222-2222-4222-8222-222222222222\/[0-9a-f-]{36}\.png$/,
    );
    expect(key).not.toContain('..');
  });

  it('never reuses a key', () => {
    const keys = new Set(
      Array.from({ length: 200 }, () => buildImageKey({ ...owner, contentType: 'image/jpeg' })),
    );
    expect(keys.size).toBe(200);
  });

  it('refuses a content type it has no extension for', () => {
    expect(() => buildImageKey({ ...owner, contentType: 'application/x-msdownload' })).toThrow(
      /unsupported content type/,
    );
    expect(() => buildImageKey({ ...owner, contentType: 'image/svg+xml' })).toThrow();
  });
});
